doctrine:
    dbal:
        dbname: '%env(POSTGRES_DB)%'
        host: '%env(POSTGRES_HOST)%'
        user: '%env(POSTGRES_USER)%'
        password: '%env(POSTGRES_PASSWORD)%'
        charset: UTF8
        server_version: 13
        driver: pdo_pgsql

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
